[package]
name = "bvh"
description = "A fast BVH using SAH"
version = "0.8.0"
edition = "2021"
authors = [
    "Sven-Hendrik Haase <svenstaro@gmail.com>",
    "Alexander Dmitriev <alexander.dmitriev2580@gmail.com>",
    "Marios Staikopoulos <marstaik@gmail.com>",
]
readme = "README.md"
repository = "https://github.com/svenstaro/bvh"
documentation = "https://docs.rs/crate/bvh"
keywords = ["bvh", "bounding", "volume", "sah", "aabb"]
license = "MIT"

[dependencies]
approx = "0.5"
rand = "0.8"
log = "0.4"
serde = { optional = true, version = "1", features = ["derive"] }
num = "0.4.0"
nalgebra = { version = "0.32.2", features = ["default", "serde-serialize"] }

[dev-dependencies]
proptest = "1.0"
obj-rs = "0.7"
float_eq = "1"
doc-comment = "0.3"
parry3d = "0.13.6"

[features]
bench = []
simd = []

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1
