[package]
name = "bvh"
description = "A fast BVH using SAH"
version = "0.5.0"
edition = "2018"
authors = [
    "Sven-Hendrik Haase <svenstaro@gmail.com>",
    "Alexander Dmitriev <alexander.dmitriev2580@gmail.com>"
]
readme = "README.md"
repository = "https://github.com/svenstaro/bvh"
documentation = "https://docs.rs/crate/bvh"
keywords = ["bvh", "bounding", "volume", "sah", "aabb"]
license = "MIT"

[lib]
name="bvh_f64"
crate-type = ["rlib", "dylib"]

[dependencies]
approx = "0.4"
rand = "0.8"
log = "0.4"
num = "0.4"
glam = "0.15"
rayon = "1.5.1"
obj-rs = "0.6"

[dev-dependencies]
proptest = "1.0"
float_eq = "0.6"
criterion = "0.3"

[features]
bench = []

[profile.release]
lto = true
codegen-units = 1
debug = true

[profile.bench]
lto = true
codegen-units = 1
